### ISSUE TITLE
1.0.49 version of vk.xml causes build errors with generated vulkan.hpp

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-Hpp#105]
The enhanced-mode body for PhysicalDevice::getSurfaceCapabilities2KHR() appears to be incorrect and causes the following build errors:

```
1  VULKAN_HPP_INLINE Result PhysicalDevice::getSurfaceCapabilities2KHR( const PhysicalDeviceSurfaceInfo2KHR* pSurfaceInfo, SurfaceCapabilities2KHR* pSurfaceCapabilities ) const
2    {
3      return static_cast<Result>( vkGetPhysicalDeviceSurfaceCapabilities2KHR( m_physicalDevice, reinterpret_cast<const VkPhysicalDeviceSurfaceInfo2KHR*>( pSurfaceInfo ), reinterpret_cast<VkSurfaceCapabilities2KHR*>( pSurfaceCapabilities ) ) );
4    }
5  #ifndef VULKAN_HPP_DISABLE_ENHANCED_MODE
6    VULKAN_HPP_INLINE Result PhysicalDevice::getSurfaceCapabilities2KHR( const PhysicalDeviceSurfaceInfo2KHR & surfaceInfo ) const
7    {
8      Result result = static_cast<Result>( vkGetPhysicalDeviceSurfaceCapabilities2KHR( m_physicalDevice, reinterpret_cast<const VkPhysicalDeviceSurfaceInfo2KHR*>( &surfaceInfo ), reinterpret_cast<VkSurfaceCapabilities2KHR*>( &surfaceCapabilities ) ) );
9      return createResultValue( result, surfaceCapabilities, "vk::PhysicalDevice::getSurfaceCapabilities2KHR" );
10   }
11 #endif /*VULKAN_HPP_DISABLE_ENHANCED_MODE*/
```
Line 8: 'surfaceCapabilities': undeclared identifier
Line 9: 'surfaceCapabilities': undeclared identifier

**Comment by mtavenrath** [comment]
@mark-lunarg Mark, getSurfaceCapabilities2KHR does not have any success codes, but only error codes which is unlike a desired behavior and should be fixed in the vk.xml. If we'd be able to generate this function it'd still be useless since it'll always throw an exception unless there's at least one success code.

We'll replace the assertion we have in the generator code by an exception to have validation coverage here so that this type of bug will be discovered more easy in the future.

Closing as this is not a Vulkan-Hpp issue.

**Comment by mark-lunarg** [comment]
@mtavenrath, Thanks!  If you haven't already opened an issue on Vulkan/Vulkan, lemme know and I'll see about doing so.

**Comment by mtavenrath** [comment]
@mark-lunarg I haven't openend an issue yet.
