### ISSUE TITLE
using CStructureType = ${vkName};

### ISSUE THREAD

**Issue by snow910** [KhronosGroup/Vulkan-Hpp#1050]
Hi. I'm developing a small wrapper over your classes and ran into the problem of missing something like CType from vulkan_handles in vulkan_structs. Can I ask you to add "using CStructureType = ${vkName};" to the VulkanHppGenerator::generateStructure method?

**Comment by asuessenbach** [comment]
That's a good idea.
The handle classes already provide such a connection to the corresponding C-type, using the name "CType". Unfortunately, one structure has a member named "CType" (sic), forcing us to use a different name!
In order to have the same name here for handles and structures (and unions as well), we chose "NativeType".
