### ISSUE TITLE
Ambiguous API interface (Compiler would choose the “unexpected” one)

### ISSUE THREAD

**Issue by Destroyerrrocket** [KhronosGroup/Vulkan-Hpp#1195]
Hello! I'm aware that this issue is small, yet tricky to fix, but I believe that at least a second person will fall into this issue.

While I was porting a renderer, I needed to implement a depth-only pass. As such, I wrote this line:
`vk::SubpassDescription subpassFormatWrite({}, vk::PipelineBindPoint::eGraphics,{},{},{},&depthAttachmentRef,{});`
This, unfortunately, picks the constructor with sizes and pointers, instead of the one with the vk::ArrayProxyNoTemporaries. Of course, a solution would be to not make the vk::ArrayProxyNoTemporaries have a default constructor, but this is certainly not really an option.

The solution I'd like to propose is to define two macros that disables default constructors for each kind of constructors. That way, in my case, I could disable either both or the size+pointer constructors. Of course, this does not solve the issue immediately, as by default people will still fall into this issue. Ideally, it would be nice that the macros were the other way around: You have to define the macro to get default constructors. But making such an API break is probably not going to fly. At least with the sign-out approach, tutorials can suggest enabling this.

If you come up with a better solution (that maybe does not require yet another macro definition), or it is decided that this is enough of a non-issue to not bother fixing, I thank you for your time and such an amazing API. You've saved me more time than this issue has taken. :)

Environment:
Windows 10
Mingw-w64 gcc 11.2.0 posix
Vulkan SDK 1.2.198.1

**Comment by asuessenbach** [comment]
Hi @Destroyerrrocket, thanks for reporting this issue.
Unfortunately, I don't see a solution to it!
Actually, the problem is the **lack of ambiguity** here. If the compiler would not silently select the constructor with sizes and pointers, but would spit out some error (or at least a warning) about ambiguity, everything would be fine. You could identify the issue and construct your object in an unambiguous way.
And I don't see any means to tell the compiler to consider the other constructor as well.
And I can't even put an assertion into the sizes/pointers-constructor, that pColorAttachments is not a nullptr, but colorAttachmentCount is zero. Maybe the user just wants to set the pointer to the colorAttachments, and determine the number of attachments to use at some later point in code.
And I even doubt that any validation layer might catch that situation, as I think it's totally valid to have colorAttachmentCount == 0 and pColorAttachments != nullptr.

That is, after all: I don't have a solution to this issue.
And introducing some define to exclude the one or the other constructor is probably too heavy-weight.

**Comment by Destroyerrrocket** [comment]
Yeah, I also saw that it was probably not going to be fixable without removing the default constructors. Thank you a lot for also considering the issue from the Vulkan perspective as well! You're free to close the ticket, I just wanted to make sure it was at least aknowledged.

**Comment by Destroyerrrocket** [comment]
(woops, I meant default parameter values instead of default constructors in all the posts I made. Sorry for any confusion caused)
