### ISSUE TITLE
Got exception when using vk::DebugReportFlagsEXT

### ISSUE THREAD

**Issue by Xottab-DUTY** [KhronosGroup/Vulkan-Hpp#124]
Got exception on app compiled in latest Visual Studio 2017 (I got this error even earlier)
`this was 0x8`

So, this means, that this was vk::DebugReportFlagBitsEXT::eError flag. But application won't work and thinks that this is an unhandled exception.

I have this callback function:
```
static VKAPI_ATTR vk::Bool32 VKAPI_CALL vkDebugCallback(
    vk::DebugReportFlagsEXT flags,
    vk::DebugReportObjectTypeEXT objType,
    uint64_t obj,
    size_t location,
    int32_t code,
    const char* layerPrefix,
    const char* msg,
    void* userData)
{
    Warning("\nValidation layer reports: \n" \
        "Flags: not working right now \n" \
        "Object type: {} \n" \
        "Object: {} \n" \
        "Location: {} \n" \
        "Code: {} \n" \
        "Layer prefix: {} \n" \
        "Message: {} \n" \
        "User data: {}\n",
        //vk::to_string(flags),
        vk::to_string(objType),
        obj, location,
        code, layerPrefix,
        msg, userData);

    return VK_FALSE;
}
```
The problem is that I can't use vk::to_string(flags), because I'm getting an exception.

What can I do to fix this?

Should I use vk::DebugReportFlagBitsEXT instead of vk::DebugReportFlagsEXT? (asking because this works for me)

**Comment by mtavenrath** [comment]
I didn't check the assembly, but my assumption is that vk::DebugReportFlagsEXT will be passed on the stack because it's a class (with a single integer) while vkDebugReportFlagBitsEXT is an integral type which will be passed in registers. Thus you'll see a crash. 

When defining the debug callback you take the same signature as defined in the spec: https://vulkan.lunarg.com/doc/view/1.0.37.0/linux/vkspec.chunked/ch32s02.html

What's missing in Vulkan-Hpp is an explicit conversion from vk*Flags to vk::*Flags to use the vk::to_string() functions. I'll file a separate issue for this.

**Comment by Xottab-DUTY** [comment]
Thank you! Will be waiting for the update.
