### ISSUE TITLE
Failed to compile it in debian

### ISSUE THREAD

**Issue by vega0** [KhronosGroup/Vulkan-Hpp#1435]
```

-- CMAKE_CXX_STANDARD = <11>
-- Configuring done
CMake Error in CMakeLists.txt:
  Target "VulkanHppGenerator" requires the language dialect "CXX20" (with
  compiler extensions), but CMake does not know the compile flags to use to
  enable it.


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
koshmar@ACTPA:/media/koshmar/2DEDC4C311647F4A/Рабочее Пространство/cpp.машинный/Стороннее/Vulkan-Hpp$ gcc --version
gcc (GCC) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
Это свободно распространяемое программное обеспечение. Условия копирования
приведены в исходных текстах.

  Без гарантии каких-либо качеств, включая 
коммерческую ценность и применимость для каких-либо целей.


```

Failed to build it tells that can't find cxx20 but it installed manually after compiling. Why this happens?

**Comment by asuessenbach** [comment]
What version of CMake are you using? Maybe you need a newer one?

**Comment by vega0** [comment]
> What version of CMake are you using? Maybe you need a newer one?

```
koshmar@ACTPA:/media/koshmar/2DEDC4C311647F4A/Рабочее Пространство/!Машинный$ cmake --version
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by asuessenbach** [comment]
And what compiler are you using? Maybe you need to update that to get C++20 support.

**Comment by theHamsta** [comment]
@asuessenbach CXX_STANDARD 20 (set here https://github.com/KhronosGroup/Vulkan-Hpp/blob/master/CMakeLists.txt#L146) was introduced only in CMake 3.12 https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD while the generator only requires 3.2 https://github.com/KhronosGroup/Vulkan-Hpp/blob/49a288231bde0466e6a999f1448fdcf42bdcf16c/CMakeLists.txt#L27. In order to use this feature, the minimum CMake version should be set to 3.12

**Comment by asuessenbach** [comment]
Good catch!!
Will adjust it right now.
