### ISSUE TITLE
vectors of UniqueHandles lead to repeated code pattern that would be better handled in vulkan.hpp

### ISSUE THREAD

**Issue by ericberdahl** [KhronosGroup/Vulkan-Hpp#148]
The inclusion of UniqueHandle and the various uses of UniqueHandle is a wonderful feature of vulkan.hpp -- possibly the most compelling feature of the library. However, there is a coding pattern in Vulkan APIs that makes UniqueHandles slightly more wordy for the developer.

Consider a vector of UniqueDescriptorSet. A program that manages descriptor sets would use such a vector a lot, perhaps having created it from Device::allocateDescriptorSetsUnique. When that program then tries to bind the descriptors to a command buffer, perhaps through CommandBuffer::bindDescriptorSets, the developer has a problem because the API for bindDescriptorSets wants an array of DescriptorSet, not of UniqueDescriptorSet. Thus, the program needs to unwrap the vector of UniqueDescriptorSet to create a temporary vector of DescriptorSet, and then pass that temporary vector to bindDescriptorSets.

Instead, it would be much more desirable for vulkan.hpp to help the developer. At a minimum, a utility function that does the unwrapping would be handy. Even better would be if ArrayProxy could do this unwrapping, or if there were an overload of bindDescriptorSets to do this, and/or a bindDescriptorSetsUnique version (if other options are too difficult to implement). Basically, I'm trying to find the boilerplate code that every developer will write (to use UniqueHandles more pervasively) and determine a pattern to bake those patterns into vulkan.hpp.

**Comment by mtavenrath** [comment]
@ericberdahl You've found the reason why we've been hesitant to add a UniqueHandle to Vulkan-Hpp ;-) All other parts of the API come at no to little cost except the required conversion of arrays of unique handles. In fact we've been wondering if we should add support for arrays at all. In the end we decided to support them since allocation is usually rare in comparison to usage.

If we support easy unwrapping of UniqueHandle arrays directly in the ArrayProxy there's the risk that people use it even in the performance sensitive cases which I'd like to prevent. Do you have a few use-cases at hand to get an idea about the potential cost?

The biggest issue with unwrapping a vector is temporary storage of unknown size and the required allocation under the assumption that people will unwrap only a few elements at draw call time. Looking at bindDescriptorSets I see two options to avoid this cost:

1. Implement a template function and make descriptorSetCount a template parameter. The temporary array can be stored on the stack in this case. This would require knowledge of the engine on how many descriptors are in the std::vector and is a 'bigger' API change.
2. Add a std::vector/raw array for temporary storage to the function (or ArrayProxy) and let the application developer handle the temporary memory management.
3. Think about more patterns

At a first glance 2. would be my preferred solution, but I hope there's something more elegant.

**Comment by ericberdahl** [comment]
@mtavenrath I understand your hesitancy to adding UniqueHandle, but I laud the fact that you did it! The UniqueHandle pattern is one that every developer would have written on their own -- particularly interesting because of the lack of introspection in the Vulkan API and the need for the application to do explicit lifetime management of all objects. C++ programmers in particular would each have their RAII wrappers, many of which would be correct. By supplying a correct implementation in vulkan.hpp, you've added great value over "just a C++ spelling of the functions".

Similarly, the addition of vector return results and exceptions are excellent features that make vulkan.hpp feel like a true C++ interface to Vulkan, while maintaining a thin veneer over the Vulkan API (i.e. continuing to leave frameworks and middleware for readers to experiment with on their own).

I actually think that unwrapping UniqueHandle into ArrayProxy directly is dangerous, for much of the rationale you present. The best option along that direction would likely be defining yet another overload of the ArrayProxy-consuming API that would accept and ArrayProxy of the UniqueHandle flavor. That overload would unwrap the array and then call the regular ArrayProxy flavor. However, I'm not a fan of hiding at operation, even for the syntactic sugar it provides.

The best solution (at least for the moment) may be the simple addition of a helper function that will do the unwrapping. For example, I've written a simple template function that will unwrap an ArrayProxy of UniqueHandles into a vector of the equivalent (non-unique) handle elements. That allows my code to determine the best time to do the unwrapping, reusing that unwrapped vector over N Vulkan API calls as I choose, while maintaining the memory-safety of the vector of UniqueHandles being in scope (and/or cleaning up if they happen to fall out of scope).

**Comment by baszalmstra** [comment]
How about ‘alloca’? That still allows you to use arrays of unknown size.

**Comment by jeremyong** [comment]
Given that the unique handles are essentially value types, I think I prefer an explicit overload for collections of unique handles over a solution that unwraps into another temporary.

Also, I want to echo the sentiment that in general, UniqueHandle is a fantastic feature that I wish I encountered earlier.

**Comment by jeremyong** [comment]
I have another proposal, which I may be able to help implement depending on feedback (and I'm sure there may be holes in my thinking).

How about a new structure that looks like `vk::unique_vector` (or `vk::UniqueVector` for naming consistency). The way this `vector`-like class works is that is is not copyable, but it is movable. It stores elements contiguously, and deleters contiguously as well (but separately). Also, the `data` method of this class returns a pointer to the start of the elements it contains (not the deleters.

Adding to the vector is done via `emplace_back` with a moved or temporary rvalue `UniqueHandle` of some sort, and iteration and access of any sort would operate on the dereferenced contents. Finally, when the `vk::unique_vector` goes out of scope, all deleters are invoked.

Thoughts?

**Comment by jeremyong** [comment]
[Here's](https://gist.github.com/jeremyong/73a6e2ee012360592c3cfb95119bec82) a gist I made just now implementing a sketch of this idea. Code snippet using it follows:

```c++
    VkUniqueVector<vk::DescriptorSetLayout> layouts;

    for (auto& set_bindings : bindings)
    {
        layouts.emplace_back(m_device->createDescriptorSetLayoutUnique(
            {{}, static_cast<uint32_t>(set_bindings.size()), set_bindings.data()}));
    }

    m_layout = m_device->createPipelineLayoutUnique(
        {{}, layouts.size(), layouts.data(), 0, nullptr});
```

After `layouts` goes out of scope, all the descriptor set layouts are destroyed as expected.

(Note: I am using a C++17 compliant compiler)
