### ISSUE TITLE
Using generator flags instead of macros

### ISSUE THREAD

**Issue by oceantume** [KhronosGroup/Vulkan-Hpp#15]
Defines like *VULKAN_HPP_DISABLE_ENHANCED_MODE* and *VULKAN_HPP_NO_EXCEPTIONS* make the generated file a lot bigger and more complex than it could be. I believe generator flags/options should be added to the generator to replace those. Such flags can be accessible via command-line arguments like *--disable-enhanced-mode* and *--disable-exceptions*.

The downside to this is that it would add complexity to some parts of the generator.

**Comment by asuessenbach** [comment]
Using those defines in the generated header allows selection on usage time, instead of generation time. That way, there's just one header (per version), not multiple for different purposes. That is, you can't get the wrong one.
I dont' think, that the size or the complexity of the header is problematic, so I don't see any benefit in using generator flags instead.
