### ISSUE TITLE
Migrate to `fmtlib`?

### ISSUE THREAD

**Issue by sharadhr** [KhronosGroup/Vulkan-Hpp#1579]
While hacking on `Vulkan-Hpp`(#1580), I immediately noticed a lot of hard-coded strings with `${someVariable}` placeholders, which were only resolved with fairly expensive string pattern searches with `std::regex`, in runtime. 

[`fmtlib`](https://fmt.dev/latest/index.html) is a compile-time string-formatting library that supports [C++11 compilers](https://fmt.dev/latest/index.html#:~:text=GCC%204.8%2C%20Clang%203.4%2C%20MSVC%2019.0%20(2015)%20and%20more%20recent%20compiler%20version) (no need for C++20 compile-time format strings). Migrating to it could significantly simplify `VulkanHppGenerator.cpp`, potentially eliminating functions like [`replaceWithmap`](https://github.com/KhronosGroup/Vulkan-Hpp/blob/523491a7dfe5672089bf75e8da08888408c7c111/VulkanHppGenerator.cpp#L14127). Any thoughts on this?

**Comment by theHamsta** [comment]
Hi @sharadhr ! Thank you for your input!

The main maintainer of this repo is currently on vacation so I would avoid doing any architectural decisions like including additional dependencies (even though fmt can be easily fetched using a Cmake FetchConent command https://cmake.org/cmake/help/latest/module/FetchContent.html).

With the generator being written in C++20 standard (https://github.com/theHamsta/Vulkan-Hpp/blob/a5329232de5f434147437b8d43cf46d7d2b1f9a4/CMakeLists.txt#L160), would it be possible to use corresponding functions from the standard library (`std::format`)? For personal projects, I also still prefer `fmtlib`, as not all compilers have `__cpp_lib_fmt` (I believe only msvc has a full implementation which is provided by fmtlib).

Since `__cpp_lib_fmt` is used in other parts of Vulkan-Hpp (https://github.com/theHamsta/Vulkan-Hpp/blob/a5329232de5f434147437b8d43cf46d7d2b1f9a4/VulkanHppGenerator.cpp#L475-L477) would it be possible to gradually replace the custom function implementation with the standard library?

**Comment by sharadhr** [comment]
Thanks for the response, @theHamsta! 

Let me address things point-by-point...

1. According to [cppreference](https://en.cppreference.com/w/cpp/compiler_support/20#:~:text=Text%20formatting,19.29%20(16.10)*), it looks like all major compilers have landed support for `std::format` (`g++` 13, `clang` 14, MSVC `cl.exe` 19.29). 

2. I think we can begin by replacing calls to `replaceWithMap` with a direct call to `std::vformat`. I have [demonstrated this](https://github.com/sharadhr/Vulkan-Hpp/commit/b022f3f2cb82db4306a43da46e60519fc18c417e), and it compiles and runs correctly under both `cl.exe` and `clang-cl.exe`, and outputs the same `.hpp` files (there are a handful of whitespace changes that occur even without any changes, maybe the generated files need to be updated). However, this means that we have to omit the variable names between braces, which may make things a little complicated. Ergo...

3. The reason I proposed `fmtlib` instead was twofold:
   - The compiler support [mentioned in the readme](https://github.com/KhronosGroup/Vulkan-Hpp/blob/523491a7dfe5672089bf75e8da08888408c7c111/README.md?plain=1#LL16C7-L16C7) for the generator. I didn't realise it was already targeting C++20, but if this is the case, then I personally see no real reason why we shouldn't require a more recent version for the generator, since not many people will use it directly, like you mentioned. 
 
   - `fmtlib` allows for [_named_ arguments](https://fmt.dev/latest/index.html#:~:text=If%20your%20compiler%20supports%20C%2B%2B11%20user%2Ddefined%20literals%2C%20the%20suffix%20_a%20offers%20an%20alternative%2C%20slightly%20terser%20syntax%20for%20named%20arguments%3A) and `fmt::operator""a`. This will make life a little easier, since all that needs to be done is find-and-replace any instance of `/\${\w*}/` with `/{\w*}/`, and replace calls to `replaceWithMap` with the corresponding call to `fmt::vformat`.

**Comment by asuessenbach** [comment]
Do I get it right, that all you get with that fmtlib is, that we could replace calls to `replaceWithMap` by calls to `fmt::vformat`?
Is that substantially faster?

**Comment by asuessenbach** [comment]
@sharadhr Do you want to follow on with this issue? Or can I just close it?

**Comment by sharadhr** [comment]
I think it can be closed, I don't think this is particularly necessary right now.
