### ISSUE TITLE
Use cmake external projects and cmake build rules for tinyxml and the spec source

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/Vulkan-Hpp#16]
Many cmake projects will build their upstream dependencies if necessary by downloading either a binary or a source zip file, using the cmake `ExternalProject_Add` functionality.  However, this library can't be used in this way because the downloaded ZIP file doesn't contain the git submodules required to build.  

Instead of using a git submodule for the tinyxml dependency, you can use an `ExternalProject_Add` command of your own.  Instead of  using a submodule for the spec dependency, you can use a `file(DOWNLOAD ...)` command to fetch the spec XML.  This also has the advantage of allowing the build process to target a specific version of the spec at cmake configuration time by passing a command line argument to override the default spec URL.

**Comment by mtavenrath** [comment]
I understand the need to be able to download the project as zip and keep it alive for those cases. On the other side the git submodules are also quite convenient keeping the project as complete stable part as it is without having to run external scripts.

One thing I can imagine is running the 3rdparty download/build scripts if the dependencies are not in the folder hierarchy. 

Another option would be a (cmake) generator script which gets a vulkan version and which takes care of the rest.

What do you think of those options?

**Comment by jherico** [comment]
>  On the other side the git submodules are also quite convenient keeping the project as complete stable part as it is without having to run external scripts.

CMake is already a required component for creating a project file, so having CMake also download the dependencies and build them as well isn't really an 'external script'.  It's built in functionality of CMake.  You can keep the dependency as stable as desired.  If you look #17 , you'll see that the version of TinyXML it downloads is the precise commit that used to be referenced as a git submodule.  

Although I've targeted `https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/1.0/src/spec/vk.xml` for `VK_SPEC_URL`, meaning a build will fetch the most recent version of the spec, you can easily maintain stability by setting it to point at a given commit URL as well.

> Another option would be a (cmake) generator script which gets a vulkan version and which takes care of the rest.

I don't understand the distinction between what you're suggesting here and what I've done in #17 .   Can you elaborate?  

My goal here is to be able to depend on Vulkan-Hpp in other projects in the exact same way I've changed this project in my PR to depend on TinyXML.  Right now that's not possible unless I want to be trapped against whatever version of the spec was used in the particular commit I choose.  If my company has a build system which is non-trivial to update, I want to be be able to install a given version of the Vulkan SDK on all the build machines but still be able to use Vulkan-Hpp (and keep up with changes and fixes in the generator) without having to change the Vulkan SDK installation every time the spec is updated.

**Comment by mtavenrath** [comment]
>I don't understand the distinction between what you're suggesting here and what I've done in #17 . Can you elaborate?
The difference is when to fetch the dependencies. Your proposal fetches them during runtime while I've wondered if it'd be okay to have a separate (CMake) script which fetches the dependencies before running the CMake configure step.

In the end I see the following options
1) Keep everything as it is
   -> bad choice due to the issues you mentioned
2) Keep submodules, but download vk.xml and tinyxml if they're not on disk
  -> hybrid between both solutions
  -> git for development, allows local patches and full git history/local commits
  -> script for deployment, allows easy change of vk.xml in automatic build.
3) Use your script only
  - will loose git features for development
4) Add new script for deployment (cmake -DVK_XML=<path to vk.xml> -P deplay-vulkan-hpp.cmake 
  Could be spawed by any build system. Downloads tinyxml, vulkan-hpp and vk.xml.

>Right now that's not possible unless I want to be trapped against whatever version of the spec was used in the particular commit I choose.
The generator takes a path to a vk.xml as first argument (and should accept an second argument where to write the header). It does not trap you to a specific vk.xml version. The vk.xml version specified as submodule is the one we're testing with.

Currently we stay at the same Vulkan version as the LunarG loader. Since the API is quite stable now we plan to use always the latest vulkan version. People can use the history to grab the version they need in this case.

**Comment by jherico** [comment]
I will update my PR to change the default Vulkan spec URL to the same as the current one, since you're specifically targeting it based on the LunarG loader.

> People can use the history to grab the version they need in this case.

The problem with grabbing from history is that it tightly couples a particular generator version with a particular spec version, while the two should be independent.  I could be able to get any generator bug fixes and added features with any version of the spec, without having to fork the repository so that I can change the target spec.

Using the script instead of the cmake modules changes the required tools for building from git and cmake, to just cmake.  A given Vulkan-Hpp commit can still target a specific commit of both the spec and tinyxml.  The only difference is that instead of using git submodule commands to target a given upstream commit, you use an editor to change URL in the CMakeLists.txt

**Comment by FirefoxMetzger** [comment]
I also want to jump on the 'rent on submodule' train. While I find the idea of using submodules for dependency management intriguing it can easily cause some severe headache. For example take the following 'dependency tree'

    foo project
    ---- submodule: bar project 
    ---- ---- submodule: Vulkan-Hpp
    ---- ---- ---- submodule: Vulkan Doc (to generate Vulkan.hpp)
    ---- ---- ---- Vulkan.h also used in `bar` for compatibility with Vulkan-Hpp
    ---- submodule: baz project
    ---- ---- submodule: Vulkan Doc (to generate Vulkan.h)
    ---- submodule: Vulkan Doc (uses Vulkan.h in some files)

Now assume `Vulkan-Hpp` uses the `Vulkan Doc` coresponding to the LunarG version. `baz` however uses the latest `Vulkan Doc`. Suddenly we have a dependency nightmare. This can lead to pretty random (undefined) results:

* if `foo` includes `vulkan.h` before `bar` or `baz`, `foo` determines the vulkan version
* if `bar` is included first, `bar` determines the vulkan version
* if `baz` is included first, `baz` will determine the vulkan version

If any of these has different minor who knows what will happen. We might be able to work around this by compiling each and every submodule on its own, but then we essentially track dependancies manually. Yet, if we do it this way, why are we using CMake and submodules in the first place? Also we successfully created 3 full copies of `Vulkan Doc` within our project, which is probably not good.

Instead we can use one of the following options for the vulkan-hpp:

* Download the required `vk.xml` like @jherico suggested
* Use `find_package(<package> <version> REQUIRED)` with a user specific `Find<package>.cmake`

Latter makes `tinyXML` and the `Vulkan Doc` aviable as an importet target on which `vulkan Hpp` can depend. While this forwards responsibility to the user (has to manage the .cmake files supplying the dependencies), integration is much simpler. 

We simply assume the root project added the two .cmake files to the `CMAKE_MODULE_PATH` (or they are added elsewhere) and when any of `vulkan-hpp`'s, `foo`'s, `bar`'s or `baz`'s CMakeLists.txt is evoked they will all depend on the same thing. Similary changes to `Vulkan Doc` will not require us to update it in 3 different places. If any dependency is not there, CMake will handle the moaning and raise the appropriate error (unless set to ´QUIET´).

In this scenario, if any target's required version is not `COMPATIBLE`, we will know right off the bat. This makes housekeeping much less of a problem.

**Comment by oddhack** [comment]
Couple of heads-up about this. The next public release of the spec (probably later today) will switch to what we're calling the "single-branch model" where extensions are incorporated via asciidoc conditionals, rather than keeping them in separate branches, which was proving to be a maintenance nightmare. In and of itself that shouldn't affect you - I don't think you actually use the spec source, do you? There will be a followon change in the next release in which the explicit \<usage\> tags in vk.xml get pulled into the spec source, so vk.xml will get a lot smaller, but I don't think any information you care about will go away. Finally, we're thinking about whether to split the src/spec directory containing vk.xml into a separate repo or not. In the single-branch model there's less need for our purposes, but other consumers such as this project might find it more appealing. Let me know if you have any related thoughts.

**Comment by oddhack** [comment]
@mtavenrath ISTM this can be closed - there have been no updates in nearly four years, and the associated MR was closed a while back as well.
