### ISSUE TITLE
noexcept for UniqueHandle and handle types?

### ISSUE THREAD

**Issue by markgarcia** [KhronosGroup/Vulkan-Hpp#165]
I would like to work on marking `UniqueHandle` operations, especially the constructors and destructor, as `noexcept`. As far as I can see, `vk::Device::destroy*`  functions don't throw anything and return `void`.

There are a couple of ways that I can think of on how to go about implementing this:

* Just mark them as `noexcept` and just assume that no destroy operations will throw.
* Add introspection to `UniqueHandleTraits` to see if underlying destroy/deleter operation is `noexcept` and have `UniqueHandle` operations base on that.
* Have `UniqueHandle` operations which calls the deleter type's `destroy` function depend on whether that `destroy` function is `noexcept`. Furthermore, have the `destroy` function base on its corresponding `vk::Device::destroy*`'s `noexcept`-iness.

I would like to know if my assumption about destroy operations is correct and on your preference on how to implement this.

**EDIT 1:** Additionally, `noexcept` for (non-`Unique`) handle types?

**Comment by mtavenrath** [comment]
This is a good suggestion. In general we should mark all functions which do not throw an exception as noexcept. In case of disabled exceptions this would be the case for all functions.

>Just mark them as noexcept and just assume that no destroy operations will throw.
It's a valid assumption to destroy operations not throwing. I haven't seen a destroy operation which returns an error code in Vulkan yet and if such a thing will ever arrive we can implement specialized code.

**Comment by AI221** [comment]
This causes me problems as well, as a class containing a UniqueHandle<...> cannot be stored in a vector without some kind of indirection (e.x. unique_ptr)

**Comment by nyronium** [comment]
I had the same issues today, and so I have implemented a [draft PR](https://github.com/KhronosGroup/Vulkan-Hpp/pull/338) to address this problem. A `noexcept` destructor of `UniqueHandle` is also possible for 99% of all cases, but there exists a small set of functions that can throw in the destructor (e.g. `freeDescriptorSets`), which could be solved by using conditional `noexcept`. You can have a look at the PR for more information

**Comment by johannesugb** [comment]
This is a very important issue and the [pull request](https://github.com/KhronosGroup/Vulkan-Hpp/pull/338) from @nyronium should be merged as soon as possible in my opinion. Although not all issues are completely sorted out (see PR description), adding the PR in the current state would improve the situation already a lot.

I had a huge problem with move-only types (similar to `vk::UniqueHandle`), namely that during `std::vector::emplace_back`, it would not choose the move constructor but the copy constructor because of missing `noexcept` specifiers. In my particular case, it boiles down to not having `noexcept` assignment operators for for the `vk::Flags` which caused my compiler (MSVC) to not being able to take the branch which is labeled "strong guarantee" and calls only a move. An excerpt from the `vector` source, where it failed:

```
    template <class... _Valty>
    pointer _Emplace_reallocate(const pointer _Whereptr, _Valty&&... _Val) {
        // reallocate and insert by perfectly forwarding _Val at _Whereptr
        // [...]
        if (_Whereptr == _Mylast) { // at back, provide strong guarantee
            _Umove_if_noexcept(_Myfirst, _Mylast, _Newvec);
        } else { // provide basic guarantee
            _Umove(_Myfirst, _Whereptr, _Newvec);
            _Constructed_first = _Newvec;
            _Umove(_Whereptr, _Mylast, _Newvec + _Whereoff + 1);
        }
        // [...]
    }
```

The [PR](https://github.com/KhronosGroup/Vulkan-Hpp/pull/338) from @nyronium fixes all my issues. Thank you so much for creating it! And please merge into master soon!

**Comment by johannesugb** [comment]
Any news on this (very important issue)?

**Comment by nyronium** [comment]
@johannesugb In my PR I have pointed out some missing parts (mainly minor inconsistencies and design decisions), for which I have presented some solutions and asked for the opinion of the project maintainers. This is the reason why it is still a draft PR. Unfortunately though, I haven't got any response from the project maintainers yet.

**Comment by nyronium** [comment]
Therefore, I have decided to solve the remaining cases and mark [my pull request](https://github.com/KhronosGroup/Vulkan-Docs/issues/1070) to be feature complete.
