### ISSUE TITLE
vulkan_video.hpp is missing include guard

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-Hpp#1721]
`vulkan_video.hpp` does not compile, because it is missing the top part of the include guard:

```
#ifndef VULKAN_VIDEO_HPP
#define VULKAN_VIDEO_HPP
```

**Comment by oddhack** [comment]
I have an internal MR to improve the CI hpp-compile step to include this header going forward, which I'll merge after this has been fixed. If there are any other missing Vulkan-Hpp headers that should be tested (by tests/hpptest.cpp in the Vulkan-Docs repo), please let me know.

**Comment by asuessenbach** [comment]
Thanks for reporting this issue. The fix is on its way...
And, indeed, there are a couple of files that might be worth to also be included in that hpptest.cpp:
```
vulkan_extension_inspection.hpp
vulkan_format_traits.hpp
vulkan_hash.hpp
vulkan_raii.hpp
vulkan_shared.hpp
vulkan_static_assertions.hpp
```
Moreover, I would suggest to make that code a bit more "Vulkan-Hpp-like" by replacing
```
    vk::Instance instance;
    vk::createInstance(&instance_info, nullptr, &instance);
```
with just
`    vk::Instance instance = vk::createInstance(instance_info);
`
