### ISSUE TITLE
Attempting to create a `std::unordered_set<vk::PhysicalDevice>` results in an error

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/Vulkan-Hpp#1757]
Tried to create an unordered set of physical devices, and got the following error on MSVC 2022

`std::_Uhash_compare<_Kty,_Hasher,_Keyeq>::_Uhash_compare(const std::_Uhash_compare<_Kty,_Hasher,_Keyeq> &)': attempting to reference a deleted function`

This code is enough to trigger it:

```
        std::unordered_set<vk::PhysicalDevice> physicalDevicesX;
        physicalDevicesX.insert(nullptr);
```

Switching to `std::unordered_set<VkPhysicalDevice>` is enough to work around it for now.

**Comment by theHamsta** [comment]
std::hash isn't implemented for the opaque object vk:: PhysicalDevice, but it is for VkPhysicalDevice which is just defined as a pointer to object. The error message refers to the comparison operator which is also deleted for vk::PhysicalDevice. It would be possible to add those to operations to the opaque handles, the question would be whether they would do the expected thing (testing for pointer equality instead of value equality). Hash/comparison are implemented for vulkan structures where they test for value hash/value equality.

**Comment by jherico** [comment]
is there a good reason not to implement `std::hash<vk::PhysicalDevice>` in terms of `std::hash<VkPhysicalDevice>`?  And for all the other opaque handle types?

**Comment by asuessenbach** [comment]
Just `#include <vulkan/vulkan_hash.hpp>` and you're done.

I moved the hashing support into a separate header as not so many need to use vulkan structures or handles in `std::unordered_[map|set]` and I wanted to keep the other headers small ;)
