### ISSUE TITLE
vk::SystemAllocationScope does not "inherit" from VkSystemAllocationScope

### ISSUE THREAD

**Issue by qbojj** [KhronosGroup/Vulkan-Hpp#1758]
The `enum class vk::SystemAllocationScope` does not 'inherit' from the `enum VkSystemAllocationScope` so there is no automatic conversion between the two.

That would mean that when using `vk::AllocaitonCallbacks::pfnAllocate` you need to explicitly cast the scope to the C type.

Is it by design or just an oversight?

**Comment by asuessenbach** [comment]
It is by design.

With `enum class`es, you don't have 'inheritance' but 'underlying type', which essentially provide the size for that `enum class`.
All the bitmasks in Vulkan-Hpp (like `vk::FormatFeatureFlagBits`) use the corresponding flags-type from the C-API (here: `VkFormatFeatureFlags`) as the underlying type, which actually map to either `VkFlags` or `VkFlags64`, which means `uint32_t` or `uint64_t`, respectively. That is, the bitsmasks of Vulkan-Hpp have either 32 bits or 64 bits.

For all the non-bitmask `enum class`es (like `vk::SystemAllocationScope`), there's nothing like the flags-type from the C-API. The corresponding type from the C-API (here `VkSystemAllocationScope`) is itself an `enum`, and an `enum` can't be used as the underlying type of an `enum class`.
