### ISSUE TITLE
Standalone header and optional static library

### ISSUE THREAD

**Issue by elviras9t** [KhronosGroup/Vulkan-Hpp#198]
I have an idea to unload the size of Vulkan-HPP by using an optional static library. In addition, this will expand the capabilities of Vulkan-HPP as a stand-alone Vulkan API library for C ++.

**Comment by Wunkolo** [comment]
Would be cool to have a `CMakeLists.txt` or configurable `VulkanHppGenerator` for the generated header file so that people that use Vulkan-Hpp as a stand-alone dependency/submodule for a project can configure it to be header-only or statically linked.

There's also the [stb](https://github.com/nothings/stb) route of having a "`#define VulkanHppImplementation`" before inclusion option to allow the user to move the implementation to a cpp file.

**Comment by mtavenrath** [comment]
There is barely code in Vulkan-Hpp which can be precompiled and moved to a static library. With the addition of the template for the function indirection all functions are now template functions which have to be defined in the header.

Closing the issue.
