### ISSUE TITLE
Missing comparison operators for RAII classes

### ISSUE THREAD

**Issue by maxime-modulopi** [KhronosGroup/Vulkan-Hpp#1996]
Comparison operators are not present in the RAII classes.
Since the normal HPP classes have them, they should probably be added to their RAII counterparts too.

**Comment by asuessenbach** [comment]
You're right, the comparison operators on the RAII classes are missing. Will add them asap.
In fact, due to the implicit cast operators to the underlying Vk-handles, the comparison operators on the vk-classes aren't needed at all! They will be removed.

Thanks a lot for the hint to the missing functions!
