### ISSUE TITLE
createDeviceUnique eror

### ISSUE THREAD

**Issue by bigdimboom** [KhronosGroup/Vulkan-Hpp#202]
c:\vulkansdk\1.1.70.1\include\vulkan\vulkan.hpp(35431): error C2661: 'vk::ObjectDestroy<vk::NoParent>::ObjectDestroy': no overloaded function takes 2 arguments

compiler error occurs in visual studio 2017 when calling

vk::UniqueDevice device = physicalDevices[0].createDeviceUnique(vk::DeviceCreateInfo(vk::DeviceCreateFlags(), 1, &deviceQueueCreateInfo));

**Comment by bigdimboom** [comment]
I mean, this is a easy bug to fix. How do I contribute?

**Comment by Selmar** [comment]
It looks like this was already fixed a while ago: #192 

The 1.1.70.1 SDK installer apparently has a file that somehow does not contain this fix, though it was committed before the 1.1.70.1 changes. I guess something went wrong in synchronization somewhere.

**Comment by lenny-lunarg** [comment]
The 1.1.70 SDKs did not release using the very latest from this repo at the time. We always branch source code from master some time before release so that we can test SDKs and not worry about introducing breaking changes into the SDK during testing. This was particularly true for for the 1.1.70 SDKs, as breaking changes were far more likely with the first 1.1 SDK. As a result, we simply branched before this fix was included, so the fix should make it into the next SDK.
