### ISSUE TITLE
no destroy for SurfaceKHR?

### ISSUE THREAD

**Issue by bigdimboom** [KhronosGroup/Vulkan-Hpp#204]
I guess I can use a uniqueHandle for Surface. But the destroy method can be added to SurfaceKHR?

**Comment by mtavenrath** [comment]
Objects in Vulkan-Hpp do not have destroy functions, since they would have to store the parent object to be able to call the destroy function. The destroy function for a specific object type is in the same class as the create function for the same object type. In case for vk::SurfaceKHR, the class Instance provides the destroySurfaceKHR function.

**Comment by LWarrens** [comment]
This exists now as an instance method
