### ISSUE TITLE
Feature Request: Use ArrayProxy in *CreateInfo constructors

### ISSUE THREAD

**Issue by mbarriault** [KhronosGroup/Vulkan-Hpp#216]
The ArrayProxy class in functions like `vk::CommandBuffer::setViewport` and such has definitely proven its useful, however in the various `vk::*CreateInfo` constructors, the absence is sorely felt, with many structs having `objectCount` and `pObjects` members to specify in the constructor. It's especially notable when either `0, nullptr` or `1, &object` are so frequently used. It would be particularly useful to have an overloaded alternate constructor that replaced `uint32_t objectCount, T* pObjects` with `ArrayProxy<T> objects` as it does in the `vk::` commands.

For example, for fixed viewports,

`vk::PipelineViewportStateCreateInfo viewportState({}, 1, &viewport, 1, &scissor);`

could be replaced by

`vk::PipelineViewportStateCreateInfo viewportState({}, viewport, scissor);`

**Comment by jherico** [comment]
The reason `ArrayProxy` is used in function calls only and not in structures is that there's no guarantee that the lifetime of wrapped objects will be longer than the lifetime of the structure where the data is being used.  In fact, if you're creating an on-demand vector, then you're pretty much guaranteed the opposite.

Consider the code....

```
vk::Viewport vp1, vp2;

vk::PipelineViewportStateCreateInfo viewportState({}, {vp1, vp2}, scissor);
```

The initializer list used to construct the `ArrayProxy` leaves scope as soon as the the constructor is done, meaning the viewportState object now contains a dangling pointer.

**Comment by mbarriault** [comment]
Hm, you're right. My apologies, I should have thought of that.

**Comment by jherico** [comment]
On the other hand, I wouldn't mind seeing constructors that take vectors. If I do this...

```
std::vector<vk::Viewport>  vps { ... }
vk::PipelineViewportStateCreateInfo viewportState({}, (uint32_t)vps.size(), vps.data(), ...);
```

Then it's already my responsibility to make sure the `vps` lifetime is correct.  So `viewportState({}, vps, scissor);` just becomes syntactic sugar.  However, since you'd want the convenience of either passing a vector or a single instance, you'd still need some kind of wrapper similar to ArrayProxy, but which would only accept _pre-existing_ vectors or single instances, but not initializer lists or vectors created implicitly in the call.  I'm not sure how you'd do that.

**Comment by mbarriault** [comment]
Maybe you could overload the move versions to be a compiler error? That way you could ensure that the argument always exists outside the scope of the constructor call.
