### ISSUE TITLE
The function vk::createInstance is not being generated anymore

### ISSUE THREAD

**Issue by monamimani** [KhronosGroup/Vulkan-Hpp#24]
I was reading the header and trying to figure our how things work together when I could find what actually use a InstanceCreateInfo.  Also is seems more in missing like i couldn't find vk::Instance.

I believe this commit is the one that broke things
be9beb84ac4e023d9b6742b05aad39234d4b725c

Thanks

**Comment by mtavenrath** [comment]
@monamimani If you used the GitHub code browser to view the vulkan.hpp you won't have seen the full header due to limitations in the Viewer. The instance class is behind this limit which could be the reason why you haven't found it. To view the full header use the raw view like here: https://raw.githubusercontent.com/KhronosGroup/Vulkan-Hpp/master/vulkan/vulkan.hpp

class Instance starts at row 17350.

**Comment by monamimani** [comment]
Ok thanks,

Yes I used github code browser.

Sorry for the bad issue.


Have a good day.

**Comment by mtavenrath** [comment]
Not an issue, closing.
