### ISSUE TITLE
Convenience macro to change default dispatcher

### ISSUE THREAD

**Issue by jeremyong** [KhronosGroup/Vulkan-Hpp#247]
Per title, it'd be great to have a macro like VULKAN_DEFAULT_DISPATCH which would allow the user to specify an alternative default loader.

**Comment by WubiCookie** [comment]
Agreed, I think this is a problem when I create UniqueHandles with the DispatchLoaderDynamic. For instance, UniqueDevice is actually a UniqueHandle<Device,DispatchLoaderStatic>. I have to either use auto or declare an alias to keep a readable code.

**Comment by asuessenbach** [comment]
That's an interesting idea.
Unfortunately, that default dispatcher would have to be a stateless one, just like the DispatchLoaderStatic. Otherwise, on each function, such a default dispatcher would be instantiated, which would come for a price.
@jeremyong: So, what kind of Dispatcher do you have in mind here?

**Comment by jeremyong** [comment]
In my case, I was imagining a stateless dispatcher like `DispatchLoaderStatic` as you say which references a static instance of the dynamic dispatcher.

**Comment by asuessenbach** [comment]
But that approach would have some ordering problems:
You would have to define that VULKAN_HPP_DEFAULT_DISPATCHER before you include vulkan.hpp. That is you can not use any of the vk namespace (like vk::DispatchLoaderDynamic) in your own dispatcher.

**Comment by asuessenbach** [comment]
This has been resolved with PR #390.
