### ISSUE TITLE
Any way to change "master" branch name

### ISSUE THREAD

**Issue by JamilaErnenberg** [KhronosGroup/Vulkan-Hpp#264]
It's a little insensitive considering the past situation of our nation.

**Comment by jherico** [comment]
Assuming you're not just a trolling jackass (which is pretty hard to assume since you're using a brand new account and this is the first and only publicly visible thing you've ever done on github):

* fork the repository
* clone the fork
* branch from the existing master branch with `git checkout -b desiredName` 
* push your new branch to your fork with `git push -u origin desiredName`
* remove your local master branch with `git branch -D master`
* remove the master branch from your repository with `git push origin :master`

You'd still need to rebase off of the upstream/master if you want to keep track of changes to the main repository.  

Alternatively, if you just want to use the `vulkan.hpp` functionality, you can just grab it from the Vulkan SDK, which is a binary distribution and doesn't have a "master" term associated with it.

No one is going to boil the ocean for you.  Ff for some reason you actually give a shit about this, you'd be a lot better off creating a custom git client that automatically translates the term "master" to something more acceptable to you, rather than expecting the entire GitHub ecosystem to change for you.  You can then promote that client and hope it gain sufficient adoption that people actually consider migrating the terminology in the mainstream git client and systems.
