### ISSUE TITLE
standard library

### ISSUE THREAD

**Issue by 11000100111000** [KhronosGroup/Vulkan-Hpp#285]
Why does this library redefine types which are already in the c++ standard library?

Things like vk::UniqueHandle or vk::Optional seem redundant and error prone to me since they (as far as i can tell) just mimic std::unique_ptr and std::optional in a way that make passing the standard types to functions (again as far as i can tell) impossible.

**Comment by mtavenrath** [comment]
There are historical and technical reasons for this decision

* We tried to use std::unique_ptr instead of implementing our own vk::UniqueHandle. Unfortunately the STL of one compiler vendor was not able to handle non-pointer types in combination with a deleter which takes this non-pointer type. Due to those problems we had to implement our own version of vk::UniqueHandle.
* If all compilers would support this feature there is still the 'legacy' problem supporting older compilers. Vulkan-Hpp is designed to work with C++11 (or better a subset of C++11 which works with MSVC 2015) due to slow adoption of newer compilers in multiple industries.
* It might be possible to have a templated typedef for vk::UniqueHandle which uses std::unique_ptr on compilers with proper support. The slightly more hard thing might be ensuring that both handle version behave exactly the same to avoid fragment & compilation issues when changing the platform

* Vulkan-Hpp has to work with C++11 while std::optional got a feature in C++17. This prevents us to use std::optional in the API.

**Comment by 11000100111000** [comment]
1:) seems like a fixable bug which would only require a temporary workaround.(Which compiler vendor?)

2-4:) This could be solved by a mechanism similar to what [abseil](https://github.com/abseil/abseil-cpp) uses: If the compiler support std::optional, absl::optional is simply an alias, if not absl::optional is implemented in a compatible way.

Any thoughts on that?
