### ISSUE TITLE
DispatchLoaderDynamic doesn't now support old interface

### ISSUE THREAD

**Issue by notdatboi** [KhronosGroup/Vulkan-Hpp#289]
As it was asked in issue #268, interface of class DispatchLoaderDynamic was changed to be based on VkInstance, but overload that was based on vk::Instance was deleted

**Comment by MacGamerFR** [comment]
Hello,

Could you (the maintainers) give some arguments about the changes mades:
- Now `VkInstance` instead of `vk::Instance` as parameter (same for `VkDevice` and `vk::Device`)
- Now need to provide the fonction pointers `vkGetInstanceProcAddr` and `vkGetDeviceProcAddr` ( #268 )

So if we can dynamically link the vulkan library, why do we still have to statically link it too ?
Could a change like defining `VK_NO_PROTOTYPES` change this behavior ? (it should require to explicitely pass a `DispatchLoader` to every function call instead of the defaulted `DispatchLoaderStatic`)

Regards.

**Comment by Arthapz** [comment]
Hi
have we a macro or something to know what interface is installed ?

**Comment by MacGamerFR** [comment]
The changes appears to come with version 99 of the headers (on Arch AFAIK)
you can check header version with a macro like this:
```cpp
#if (VK_HEADER_VERSION >= 99)
```

**Comment by n8vm** [comment]
@asuessenbach The merge you accepted is breaking all projects which use the following code, posted in the official Vulkan README for these bindings.

```
// This dispatch class will fetch all function pointers through the passed instance
vk::DispatchLoaderDynamic dldi(instance);

// This dispatch class will fetch function pointers for the passed device if possible, else for the passed instance
vk::DispatchLoaderDynamic dldid(instance, device);

// Pass dispatch class to function call as last parameter
device.getQueue(graphics_queue_family_index, 0, &graphics_queue, dldid);
```

The above two definitions of DispatchLoaderDynamic are now missing. Can we either get these changes reverted, or documentation corrected?
