### ISSUE TITLE
No optional auto deletion of a object?

### ISSUE THREAD

**Issue by xXSeraphimXx** [KhronosGroup/Vulkan-Hpp#30]
Hello,
I'm still digging into Vulkan and this C++ API.

During this I saw, that there are no destructors for the objects, which is fine, because those would need more memory (maybe additional reference to the vk::Instance etc). 

Anyway wouldn't it be fine to create as _"nice to have"_ a wrapper for the vulkan objects, which takes care of their destruction? I'm thinking of an additional template class for example called "vk::Deleter<class T>" which wraps a vulkan object with the correct destroy function.

**Comment by mtavenrath** [comment]
Hello,

I'd love to add support for some kind of smart ptr which automatically destroys an object. The problem here is that the vk::Destroy* functions need the device and allocator when destroying an object. Those would have to be stored in addition to the handle.

In an ideal world we'd return an object which contains device, handle and allocator and which supports automatic conversion to the native handle and some kind of vk::scoped_handle.

```vk::Buffer b1 = device.createBuffer(...)``` would result in an untracked handle.

```vk::scoped_handle<Buffer> b2 = device.createBuffer(...)``` would result in a tracked handle which gets destroyed the b2 goes out of scope.

```vk::Buffer b3 = b2.release()``` would release the ownership.

It's not yet fully clear to me if a scoped_handle should be allowed as parameter to functions.

**Comment by xXSeraphimXx** [comment]
Thanks for answer :),
I already created a class, which can delete objects from the Vulkan C++ API if they're going out of the scope (surprisingly usage is great!). Currently I'm still smarting this wrapper but unfortunately I haven't implemented features like std::move for transfering ownership. I even have to admit, that I didn't thought of such a feature D: (Only thought that "easy" auto deletion would be enough)

**Comment by xXSeraphimXx** [comment]
My final suggest is this:
The use of a macro called "VULKAN_USE_SCOPED_HANDLING" to enable the template class:

`template<class T>`
`class scoped_handle{};`

also this macro disables default create functions and enables scoped_handle create functions like presented here:

`#ifndef VULKAN_USE_SCOPED_HANDLING`
`Result createBuffer(const BufferCreateInfo* pCreateInfo, const AllocationCallbacks* pAllocator, Buffer* pBuffer) const{...}`
`#ifndef VULKAN_HPP_DISABLE_ENHANCED_MODE`
`ResultValueType<Buffer>::type createBuffer(const BufferCreateInfo & createInfo, Optional<const AllocationCallbacks> allocator = nullptr) const{...} `
`#endif`
`#else`
`Result createBuffer(const BufferCreateInfo* pCreateInfo, const AllocationCallbacks* pAllocator, scoped_handle<Buffer>* pBuffer) const{...}`
`#ifndef VULKAN_HPP_DISABLE_ENHANCED_MODE`
`ResultValueType<scoped_handle<Buffer>>::type createBuffer(const BufferCreateInfo & createInfo, Optional<const AllocationCallbacks> allocator = nullptr){...}`
`#endif`

If that kind of scoped_handler suits our needs, I just need to adapt some things in the template class, add it to the header file, adapt the create functions and make a push request.

**Comment by xXSeraphimXx** [comment]
Yesterday I finished work on the scoped handling. Luckiy almost everything is done witg smallest overhead as possible. But Unfortunately  at functions like createGraphicsPipelines there can be a heavier overhead, because the vector of normal raw pipeline objects has to be transformed  into a vector which wraps pipeline objects. This transformation can create at creation a small overhead. The overhead can be made smaller for functions where enhanced functions are not disabled doing it with a parallel std transform http://en.cppreference.com/w/cpp/experimental/parallelism/existing#transform)

**Comment by mtavenrath** [comment]
We discussed scoped handles and decided that it's too early to integrate them for now due the risk of additional cost. 

Semantics:
The semantics of the scoped_handle must be the same as the sematics of std::unique_ptr and thus I'll call the object vk::unique_handle from now on. By supporting a unique_handle we'd have at least the following issues:

1. We'd loose source code compatibility since a unique_handle<T> must not cast to T through an implicit conversion. Otherwise you could write incorrect code like this:
```
vk::FooStruct s;
s.handle = device.createHandle(HandleCreateInfo());
```
s.handle will contain the newly created handle, but the unique_handle will destroy it at the end of the line. Due to this you'd have to write:

```
vk::FooStruct s;
s.handle = device.createHandle(HandleCreateInfo()).release();
```

2. If arrays are required as input/output one has to iterate over all elements in the arrays and convert the scoped_handles to native handles adding cost which we don't want to do in this binding

3. For most handles one has to store a device and the allocation pointer which increases the size of a handle by a factor of 3 which is most likely not desireable.

4. We don't feel good having a unique_handle which is not unique. If you want to use the unique_handle in a class to keep data alive as long as the class lives and you pass the unique_handle to a vk::FooStruct the handle is not really unique anymore. The FooStruct could live longer than the class which holds the handle which will introduce hard to detect errors.

> At least, where should I put examples, which show how to use scoped handling with Vulkan-Hpp ?

For now it'd be best if you fork the project, apply your changes and add samples in the fork and tell people about it to gather more feedback. Maybe it'd also make sense to offer the unique_handle as small library in a separate project so that it can be included on demand. 

> Parallel transform

Parallel transform should be used only for very large counts. For small counts the cost of multi threading synchronization will be most likely bigger than the cost of the conversion.

**Comment by andrewjw1995** [comment]
For those that are interested, the Rust project ['Vulkano'](https://github.com/tomaka/vulkano) does offer this feature. Keep in mind the project has different goals to Vulkan-Hpp - "The purpose of vulkano is not to draw a teapot, but to cover all possible usages of Vulkan and detect all the possible problems". This does mean a bit more runtime overhead.
