### ISSUE TITLE
Singular overloads of allocateCommandBuffers, allocateDescriptorSets, etc

### ISSUE THREAD

**Issue by mbarriault** [KhronosGroup/Vulkan-Hpp#323]
Vulkan.hpp currently provides a convenient set of overloads for functions like `vkCreateGraphicsPipelines` that allows one to cleanly create singular, `vk::Device::createGraphicsPipeline`. It would be helpful if this design could be extended to other creation/allocation functions that return multiples. This would be particular useful for the `Unique` versions. Right now, allocating a singular command buffer allocation requires extra boilerplate.

    auto commandBuffer = std::move(device.allocateCommandBuffersUnique(allocateInfo).front());

Ideally, this could be written

    auto commandBuffer = device.allocateCommandBufferUnique(allocateInfo);

**Comment by asuessenbach** [comment]
I'd love to introduce such functions. But other than vkCreateGraphicsPipelines, the number of objects to create is not a dedicated argument, that can be set by the special singular function. Instead, the number of objects is encoded as part of a structure. And then it's not clear how to react in such a singular function, if the structure tells me to create more than one element. Should it silently reduce it to one? Or is that an error that's worth to throw an exception?
Because of such uncertainty, we decided to not introduce singular versions of functions, where the number of objects is encoded inside a structure.

**Comment by mbarriault** [comment]
I would expect it to behave similarly as calling, eg, `vkAllocateCommandBuffers` with an under-allocated `pCommandBuffers` array. Perhaps that should be how it should be implemented, not bothering to check `pAllocateInfo`. As far as I know, it's not Vulkan.hpp's job to protect users from their mistakes, but to provide a convenient higher level API equivalent.

**Comment by asuessenbach** [comment]
Well, not exactly. One feature of vulkan.hpp I'd consider as important is, that it's harder to get it wrong.
For example, you can't under-allocate commandBuffers with the enhanced functions of vulkan.hpp (besides running low on memory, but that's a different story).
