### ISSUE TITLE
RAII "vulkan-c-bindings-reloaded"

### ISSUE THREAD

**Issue by Unarmed1000** [KhronosGroup/Vulkan-Hpp#34]
After reading your blog entry "vulkan-c-bindings-reloaded" I noticed your section on RAII. But nothing in the RAII principle require ref counting at all. It is only required if you want to do a smart pointer style thing. A more natural fit would be a unique_ptr style deal.

For a example implementation take a look at

https://github.com/Unarmed1000/RapidVulkan

**Comment by mtavenrath** [comment]
We've also thought about adding only a unique_ptr to the header file. We decided against doing so because of several reasons:

- The 'usable' lifetime of such an object is small since usually one would assign the created object to a struct after a few lines of code which results in a release call
- Each object has to hold a device and an allocation pointer for the release call. This would bloat all the handles by a factor of 3. 
- When destrucing the unique pointer it's possible that the device has already been destructed. In this case the destructor/release call of the unique pointer will crash
- If you add the device handle to the objects and you want to pass an array you've to create a temporary array and call release on all the objects which might be costly. An alternate solution would be having a separate unique_ptr object which holds the device handle and allocation pointer so that at least arrays can stay binary compatible.

Since we do like RAII programming we're working on a C++ layer on top of Vulkan-Hpp which supports refcounting as transparent as possible on top of the Vulkan API. This feature will come at a cost and is mostly useful if DescriptorSets and CommandBuffers are reused as much as possible.

**Comment by Unarmed1000** [comment]
Thanks for answering :)

- 'Usable' lifetime: A similar API has in-fact been used to convert many of Sascha Willems and a few of Norbert's samples successfully with no such issues. The initial conclusion was the code got simpler. The way to use this is to keep the RAII object around and just assign the handle to struct as well. Lifetime issues will be no harder to manage than using the C API, but it solves issues with exceptions and automatic cleanup. Yes its not as 'secure' as ref counting, but we are talking about a very low level API here so this should be within the capabilities of people that can use Vulkan.  Any one else can easily do their own implementation that for example use std::shared_ptr for the ref counting if they need it.  
- 3x bloat this will most likely not be a issue on today's hardware even on most embedded systems the sizes we are talking about are small and for some things like CommandBuffers the cost is shared between the number you decide to allocate at a time. Most systems that are that memory constrained would probably not be using exceptions either. 
- 'destruction' its no worse than using the C API, and deals with exceptions much better. 
- I will probably need more details about the last point, but it does not seem to be a issue I encountered so far using a similar API.

The samples I have been working on are not released on github yet, but I am allowed to share some of the source already if you are interested in taking a closer look at how such a solution would be used in a existing sample.

**Comment by mtavenrath** [comment]
I'll check how the samples use RAII in a nice manner and will come back to this thread alter.

**Comment by mtavenrath** [comment]
I did some analysis on the generated code and it should be possible to change ResultValue so that it returns all values required to create a unique_ptr without any cost if those values are not required. This way the unique_ptr could start as external project until it's mature and accepted.

I.e. for all objects created by a device one could return a template<Object> struct<Object> containing Device, Allocator and Object with an implicit conversion to Object to keep source code compatibility. The unique_ptr could accept this struct and initialize itself with the required values while the 'legacy' code would just cast to Object. Due to the inliner and optimizer the legacy assembly generated for the legacy code shouldn't change.

**Comment by mtavenrath** [comment]
We've added a UniqueHandle and the corresponding createXXXUnique functions. Closing.

**Comment by Unarmed1000** [comment]
Sounds good.
Also I am finally able to show some of Sasha's code converted to use RAII classes.

https://github.com/NXPmicro/gtec-demo-framework/tree/master/DemoApps/Vulkan/ComputeParticles
