### ISSUE TITLE
Get underlying handle on the HPP header

### ISSUE THREAD

**Issue by Makogan** [KhronosGroup/Vulkan-Hpp#351]
Sometimes, for debugging purposes, or merely to interface the C like vulkan API with the HPP wrappers, one may need to access a handle. 

In C, the handle can be obtained by typecasting the object into a uint64. e.g (uint64_t)device.

This however cannot be done with the HPP headers. Forcing developers to first typecast their structures to teh underlying C type and then into the uint64.

It would be easier to write generic code if the intermediary step could be avoided and instead we could directly get the handle from the HPP wrappers.

For example as 
```

vk::Device device;
device.get_handle();
```

**Comment by mtavenrath** [comment]
There is already a mechanism to get the handle using a static_cast. In your case you should be able to write:

```
vk::Device device;
uint64_t handle = uint64_t(static_cast<VkDevice>(device));
```

For convenience one could write a template which does the conversion. To make such a template generic  we're going to add a CType which allows a generic conversion routine so that one can implement

```
template <typename T>
uint64__t handle getVulkanHandle(T const &cppHandle) {
  return uint64_t(static_cast<T::CType>(cppHandle));
}
```

That said C-Style casts are dangerous and should be replaced by C++ style casts ;-)

**Comment by mtavenrath** [comment]
T::CType has been added to all Vulkan handles. A T::get_handle() function will not be added since it does not add any new functionality.

**Comment by Makogan** [comment]
From which version is this change available? I am unable to get the underlying type through for example.

SurfaceKHR::CType on 1.1.1.108.0
