### ISSUE TITLE
Is it safe to do local patch to Vulkan SDK to use the latest Vulkan-Hpp?

### ISSUE THREAD

**Issue by Krantz-XRF** [KhronosGroup/Vulkan-Hpp#408]
It seems that the official Vulkan SDK (from [LunarXchange](https://vulkan.lunarg.com/sdk/home)) is not updated so rapidly as to include the latest features of `Vulkan-Hpp`. If I really need these features immediately, all I can think of is to modify the header myself. So, generally speaking,

1. Is it safe to clone this repo and manually replace the `<vulkan.hpp>` file in the SDK?
2. Is there any guarantee that `vulkan/vulkan.hpp` in the `master` branch of this repo is always ready to be used in projects?
3. Will this replacement of file ever cause any subtle incompatibility issues?
4. Are there any officially supported methods to update `Vulkan-Hpp` in the installed Vulkan SDK?

**Comment by mtavenrath** [comment]
> 1. Is it safe to clone this repo and manually replace the <vulkan.hpp> file in the SDK?
Sometimes. The header version of vulkan.hpp must match the header version of vulkan.h. Most of the time the versions will differ. It's always save to clone the vulkan-hpp repository and generate vulkan.hpp for the same vulkan version as the SDK.
> 2. Is there any guarantee that vulkan/vulkan.hpp in the master branch of this repo is always ready to be used in projects?
What kind of guarantee do you expect? We consider the master branch as 'stable' branch. There's always the small risk of new features breaking subtle things which will be fixed upon notice ASAP.
> 3. Will this replacement of file ever cause any subtle incompatibility issues?
The honest answer to such a question has to be 'no'. Every change has the risk to create a subtle incompatibility issue, especially when adding new features for newer compilers, e.g. if the #ifdef to enable the feature wasn't strict enough.

Our philosophy is to stay source-code backward compatible so that new versions of the header can be updated at any time in projects. There are no plans to break this compatibility consciously.
> 4. Are there any officially supported methods to update Vulkan-Hpp in the installed Vulkan SDK?
1. Compile Vulkan-Hpp
2.  Download vk.xml for the SDK version used to build the Vulkan-SDK
3. VulkanHppGenerator <path to vk.xml>
4. Replace vulkan.hpp in the SDK with the newly generated header in the vulkan folder.

**Comment by Krantz-XRF** [comment]
Thanks, that really helps. I will close this issue then.

By the way, you might want to add these steps to `README.md`, so that others would find them easily.
