### ISSUE TITLE
Simple vulkan program breaks when using default dynamic loader

### ISSUE THREAD

**Issue by MythreyaK** [KhronosGroup/Vulkan-Hpp#464]
Vulkan SDK version: 1.1.130.0

Steps to reproduce: 
1. Use the visual studio Window C++ template. Change the start of the file such that it reads,
```
#define SDL_MAIN_HANDLED

#define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1
... other includes ...
#include <vulkan/vulkan.hpp>

#include <iostream>
#include <vector>

VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE

int main() { ...
```
2. Notice a null exception triggered at line 59290 in `vulkan.hpp`

I'm hoping this isn't caused by a noobie mistake, if so, I'm not sure what the error is.

**Comment by lenny-lunarg** [comment]
What's happening in your setup is that while you're creating the dynamic dispatch storage, you're using the default constructor to initialize the dispatch parameters to zero. I was able to get this working by changing the line:

```cpp
VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE
```

to:

```cpp
namespace VULKAN_HPP_NAMESPACE { DispatchLoaderDynamic defaultDispatchLoaderDynamic(&vkGetInstanceProcAddr); }
```

After instance creation, I also had to add a line:

```cpp
vk::defaultDispatchLoaderDynamic = vk::DispatchLoaderDynamic(instance, &vkGetInstanceProcAddr);
```

This works because I'm manually initializing the dispatch table to get around the lack of initialization. I suspect that using this method, you'd have to initialize again after device creation.

Also, I doubt this is a good long term solution. Someone who works on vulkan.hpp more could probably offer a better solution, but I was really just testing to make sure the SDK templates didn't have a bug in them. I don't know what the proper solution would be.

**Comment by MythreyaK** [comment]
I initialized it as suggested in readme.md
```
auto procAddr = dynamicLoader.getProcAddress<PFN_vkGetInstanceProcAddr>("vkGetInstanceProcAddr");
VULKAN_HPP_DEFAULT_DISPATCHER.init(procAddr);
```

Also, doesn't the macro itself expand to 
```
namespace VULKAN_HPP_NAMESPACE { DispatchLoaderDynamic defaultDispatchLoaderDynamic; }
```

**Comment by MythreyaK** [comment]
After further digging around, I was able to get this working. It was a mistake on my end. 
Thank you for your help!
