### ISSUE TITLE
Consider to explicitly set underlying type for FlagBits

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-Hpp#507]
Currently `static_assert(std::is_same_v<std::underlying_type_t<vk::*FlagBits>, int>);`, but "underlying type" (second template specialization argument) of corresponding `vk::*Flags` is `Vk*Flags` which is always defined as `VkFlags` or in turn `uint32_t`.
Sometimes there is need in bit arithmetic (e.g. shift) on, say, `vk::QueueFlags`' (to find best matching queue family) underlying type. `std::underlying_type_t<vk::QueueFlags>` is (signed!) `int`, but bit operations are non-UB only for unsigned arithmetic types.
I would suggest to add explicit _enum-base_ to every `enum class` definition, e.g.:
`enum class QueueFlagBits : uint32_t`
or
`enum class QueueFlagBits : VkQueueFlags`

**Comment by mocabe** [comment]
Since flags are defined like `QueueFlags = Flags<QueueFlagBits, VkQueueFlags>`, I thinks it's more consistent to write as  `enum class QueueFlagBits : VkQueueFlags`.
Or, you can detect underlying type in `vk::Flags` using `std::underlying_type`, instead of explicitly passing base type as template parameter.

**Comment by tomilov** [comment]
In light of ["Signed integers are two's complement"](https://wg21.link/p1236r1) (currently [implemented](https://clang.llvm.org/cxx_status.html#cxx20) in clang) it may have no sense.
