### ISSUE TITLE
 __declspec(dllimport) extern DispatchLoaderDynamic defaultDispatchLoaderDynamic?

### ISSUE THREAD

**Issue by wumo** [KhronosGroup/Vulkan-Hpp#624]
I'm writting a thin wrapper for vulkan-hpp as a shared library. The users of my library can choose to use original `vulkan.hpp` when my library is not enough. However `unresolved external symbol "class vk::DispatchLoaderDynamic vk::defaultDispatchLoaderDynamic"` will arise because the `extern DispatchLoaderDynamic defaultDispatchLoaderDynamic` is not specified as `__declspec(dllimport) ` or  `__declspec(dllexport) ` which is required on windows. `VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE` is defined in my library.

I'd like some predefined macro as: 
```c++
#ifdef _WIN32
    #ifdef VULKAN_EXPORTs
        #define VULKAN_EXPORTED  __declspec( dllexport )
    #else
        #define VULKAN_EXPORTED  __declspec( dllimport )
    #endif
#else
    #define VULKAN_EXPORTED
#endif
VULKAN_EXPORTED extern DispatchLoaderDynamic defaultDispatchLoaderDynamic;
```

**Comment by mtavenrath** [comment]
Can you elaborate what you are trying to achieve exactly? vulkan-hpp is designed as header so that most of the functions get inlined to not introduce additional calling overhead and the few remaining functions like the function fetching for the loader are most likely instantiated only once in a typical program.

**Comment by wumo** [comment]
I'm going to provide an wrapper library that reduces some boilerplate codes of creating and updating vulkan objects. If this library is compiled as dll on windows, the `DispatchLoaderDynamic defaultDispatchLoaderDynamic` declared and instantiated in my dll won't be seen by the library consumers unless the symbol is exported. In this situation, users of my dll can't use original vulkan-hpp functions such as `d.vkCreateFramebuffer` because `VULKAN_HPP_DEFAULT_DISPATCHER` is not exported.

Actually I just need one macro symbol `VULKAN_EXPORTED ` added before the declaration of `defaultDispatchLoaderDynamic` and let the user define what `VULKAN_EXPORTED ` actually is, `__declspec( dllimport )` or `__declspec( dllexport )`.

**Comment by jagoly** [comment]
Current solution only works with windows+msvc, and not with gcc/clang and -fvisibility=hidden.

Would be better to just allow the user to define VULKAN_HPP_STORAGE_API themselves, like most libraries do.

The solution seems simple: wrap the `#if defined(_WIN32) && defined(VULKAN_HPP_STORAGE_SHARED)` block in an `#ifndef VULKAN_HPP_STORAGE_API` block. Like the blocks above and below it.

Right now the you can't work around this at all, since it always gets overwritten.
