### ISSUE TITLE
`Device::createRayTracingPipelineNVUnique` should return `ResultValueType`

### ISSUE THREAD

**Issue by wumo** [KhronosGroup/Vulkan-Hpp#637]
As in `vulkan-headers 1.2.40`:
```
  template<typename Dispatch>
  VULKAN_HPP_INLINE ResultValue<UniqueHandle<Pipeline,Dispatch>> Device::createRayTracingPipelineNVUnique
```
is not consistent with that in `vulkan-headers 1.1.130`:
```
  template<typename Dispatch>
  VULKAN_HPP_INLINE typename ResultValueType<UniqueHandle<Pipeline,Dispatch>>::type Device::createRayTracingPipelineNVUnique
```
which results in:
```
auto pipeline = device.createRayTracingPipelineNVUnique(pipelineCache, info).value;
```
instead of:
```
auto pipeline = device.createRayTracingPipelineNVUnique(pipelineCache, info);
```

**Comment by asuessenbach** [comment]
That change was introduced because the logic of the function vkCreateRayTracingPipelinesNV did change: in addition to VK_SUCCESS (vk::Result::eSuccess), there is also VK_PIPELINE_COMPILE_REQUIRED_EXT (vk::Result.:ePipelineCompileRequiredExt) specified as a success code. That results in a change of the return type for the C++-function, but not for the C-function.

**Comment by wumo** [comment]
Alright, I'll just have to use `vk::UniquePipeline` to trigger implicit cast. 

This issue can be closed.
