### ISSUE TITLE
Default line width causes drawState error

### ISSUE THREAD

**Issue by ioquatix** [KhronosGroup/Vulkan-Hpp#64]
https://github.com/KhronosGroup/Vulkan-Hpp/blob/43ec5d8ea9e0bc4727c6a70cf7e1a2f2f829c414/vulkan/vulkan.hpp#L7079

causes

[T+0.098 main   ERROR] DS Attempt to set lineWidth to 0.000000 but physical device limits line width to between [0.500000, 10.000000]! 

Is there a reasonable default (e.g. 1?)

**Comment by asuessenbach** [comment]
Unfortunately, vk.xml does not specify any defaults.
And I don't see, how one could derive some default that's more meaningful than just zero. I would have expected that value to be supported on every platform, at least as a value with some special meaning.

**Comment by ioquatix** [comment]
Yeah, that makes sense. Unfortunately, as a default, it's not valid at least on this hardware.

**Comment by mtavenrath** [comment]
During the last Khronos Vulkan DevU event the idea came up to something like a 'vk_defaults.xml' file where one could define multiple useful default parameters for CreateInfo structs. This file could be used to create a factory library which would allow you to write something like:

```foo::createComponentMapping(foo::ComponentMapping::RGBA)```
or 
```foo::createComponentMapping(foo::ComponentMapping::BGRA```

The idea is to have reasonable defaults for all objects where applicable with the option for developers to define their own default values. 

One question which comes up if Vulkan-Hpp should use this file too for the default values. Since this will affect source code compatibility unfortunately I'd have to say no.

**Comment by ioquatix** [comment]
@mtavenrath That's an awesome idea.

If you are worried about source code compatibility, I guess I could relate. But:

1/ Bump major version?
2/ It hasn't been a problem in the past? (major changes to header breaking existing code)
3/ Make it optional?

**Comment by mtavenrath** [comment]
Default values should be implemented outside of Vulkan-Hpp in a factory-like utility library. Closing.
