### ISSUE TITLE
Implicit conversion of ResultValue<Pipeline> to Pipeline not working

### ISSUE THREAD

**Issue by saljic** [KhronosGroup/Vulkan-Hpp#659]
vk::Pipeline _graphicsPipeline;

...

_graphicsPipeline = _device.createGraphicsPipeline(nullptr, graphicsPipelineCreateInfo);

for some reason this fails with 'operator =' is ambiguous.

vulkan version 1.2.141.2

**Comment by mocabe** [comment]
This should be fixed in #618.

**Comment by asuessenbach** [comment]
Unfortunately, that use case is not handled correctly with #618.

That root-cause for this issue was introduced because the logic of the function vkCreateGraphicsPipelines did change: in addition to `VK_SUCCESS` (`vk::Result::eSuccess`), there is also `VK_PIPELINE_COMPILE_REQUIRED_EXT` (`vk::Result::ePipelineCompileRequiredExt`) specified as a success code. That results in a change of the return type for the C++-function, but not for the C-function.

I would recommend to define `VULKAN_HPP_DISABLE_IMPLICIT_RESULT_VALUE_CAST`. That doesn't resolve the issue, but makes it explicit. You then would need to explicitly handle the return code, like described here https://github.com/KhronosGroup/Vulkan-Hpp#return-values-error-codes--exceptions.

As a workaround, you might just write

```
vk::Pipeline _graphicsPipeline;
...
_graphicsPipeline = _device.createGraphicsPipeline(nullptr, graphicsPipelineCreateInfo).value;
```

**Comment by mocabe** [comment]
@asuessenbach While I understand interface change of `createGraphicsPipeline`, I still don't get why that can cause ambiguous error here. I could not repro this on gcc/clang on linux, do you think this is MSVC specific?

**Comment by tksuoran** [comment]
I have the same issue. I think #665 is good thing to do.
