### ISSUE TITLE
createComputePipeline no option to return non-ResultValue

### ISSUE THREAD

**Issue by axsaucedo** [KhronosGroup/Vulkan-Hpp#706]
When running the `<device>.createComputePipeline(<pipelineCache>, <computePipelineCreateInfo>)` I have noticed that I am only allowed to receive `ResultValue`. I am able to return non-resultValues (using exception) for other `create` methods, except for this one. <s>It seems that its plural counterpart `createComputePipelines` does support non-ResultValue returns.</s> edit: it seems createComputePipelines also only allows me to return `std::vector<vk::ResultValue<vk::Pipeline>>` as opposed to initially assumed.

More specifcially, if I attempt to run:
```
vk::Pipeline pipeline = <device>.createComputePipeline(<pipelineCache>, <computePipelineCreateInfo>);
```
I get:
```
src/main.cpp: In constructor 'VulkanCompute::VulkanCompute()':
src/main.cpp:443:76: error: ambiguous overload for 'operator=' (operand types are 'vk::Pipeline' and 'vk::ResultValue<vk::Pipeline>')
  443 |                                                   computePipelineCreateInfo);
```

I'm using the with Vulkan 1.2.141.2 header files.

Thank you

**Comment by asuessenbach** [comment]
That's absolutely correct.
The reason for that difference between `create[Compute|Graphics]Pipeline `and other `create*` functions is, that all but those two functions are specified to have just one possible success value as the `vk::Result`: `vk::Result::eSuccess`.
But those two functions are specified to have more than one success value: `vk::Result::eSuccess` and `vk::Result::ePipelineCompileRequiredEXT`.
That is, in order to get that information back to the caller, we need to return a `vk::ResultValue` pair here.

**Comment by axsaucedo** [comment]
I see! Interesting, thank you for your prompt reply. This makes sense... Ok I can close this issue in this case. Really appreciate it.

**Comment by axsaucedo** [comment]
@asuessenbach I have another question which came up on https://github.com/EthicalML/vulkan-kompute/issues/67 - it seems that there are situations where createPipeline does actually return a result instead of a resultvalue, is this something that was introduced in version 1.2 by any chance? If that is the case, is there a way to add a MACRO guard based on the Vulkan versions?
