### ISSUE TITLE
Dynamic Vulkan library load?

### ISSUE THREAD

**Issue by zedrian** [KhronosGroup/Vulkan-Hpp#73]
Basic C-style **Vulkan** (via `vulkan.h`) allows loading its functions in runtime via macro `VK_NO_PROTOTYPES` and mechanism like 
```
library = LoadLibrary("vulkan-1");
some_vulkan_func = GetProcAddr(library, "some_vulkan_func");
```

Is it possible to use **Vulkan-Hpp** in the same manner or we can either load Vulkan dynamically or use **Vulkan-Hpp**?

**Comment by spfuetzner** [comment]
It would also be nice for Vulkan-Hpp to load and use the device-specific function pointers to squeeze this little extra performance out of Vulkan.

**Comment by ioquatix** [comment]
This problem is discussed here in a specific case: https://github.com/KhronosGroup/Vulkan-Hpp/issues/33

**Comment by ioquatix** [comment]
What I'd suggest is initially thinking about how we solve #33 and then using that as a general pattern for other instances of the problem.

I thought about it and one idea I came up with was to have a split implementation of `vulkan.hpp`, e.g. `vulkan.hpp` and `vulkan-ext.hpp`.

The problem is that ideally, the function pointers would be part of [members of] vk::Device, but I believe that the motivation is to keep `vk::Device` and `VkDevice` the same memory layout and size.

If that's truely the case (e.g. it's not acceptable to have a `vk::Device` with the same initial layout but additional trailing private fields, then I'd suggest we have `vk::ExtendedDevice` which DOES have these extended fields.

So, in pseudo-code:

```c++
class vk::Device {
    // same as VkDevice
};

class vk::ExtendedDevice : public vk::Device {
    PFN_vkCreateDebugReportCallbackEXT vkCreateDebugReportCallbackEXT;

    //in constructor or on demand
        vkCreateDebugReportCallbackEXT = (PFN_vkCreateDebugReportCallbackEXT)this->getProcAddr("vkCreateDebugReportCallbackEXT");

    void createDebugReportCallbackExt(...) {
        // ...
    }
};
```

**Comment by ioquatix** [comment]
The other question one wonders about is whether that this is necessary for performance or not. If you load one driver, can you assume that `vkCreateDebugReportCallbackEXT` is always the same? What about if you load two drivers? Since `vkCreateDebugReportCallbackEXT` takes a device as the first instance, in theory, internally, it would dispatch on the correct function for a specific driver.

**Comment by mtavenrath** [comment]
>then I'd suggest we have vk::ExtendedDevice which DOES have these extended fields.

Adding fields to the objects will destory the binary compatibility which will be an issue at least for vk::CommandBuffer where you have to pass arrays to Vulkan. We don't want to generate copies of arrays. In addition to this the copy-assignment of handles will get very expensive if one has to copy/fetch a hundred pointers.

With regards to performance the only extension function pointers which are of interest are the ones which operate on a command buffer. I'd be surprised if the dispatch cost of the other functions will become a bottleneck with respect to the actual cost of the (driver) implementation.

vulkan.h by default declares all the functions, so we decided to implement an extension loader which implements the functions which can be found here: https://github.com/KhronosGroup/Vulkan-Docs/tree/1.0/src/ext_loader

To generate the ext-loader with your own extensions you can call gen_vk.py from here: https://github.com/KhronosGroup/Vulkan-Docs/tree/1.0/src/spec

For each <extension> to exclude add --removeExtension <extension> to the command line.

The extension loader has vkExtInitInstance functions if multiple devices are required and vkExtInitDevice if the application is going to use a single device only. Multi-Instance support is not (yet) supported and would require some changes to the LunarG Vulkan loader.

Since vulkan.hpp is a header-only library there's no storage where to put the function pointers. Otherwise vulkan.hpp would get all the extension pointers.

**Comment by ioquatix** [comment]
I saw that. It looks good.

> Multi-Instance support is not (yet) supported and would require some changes to the LunarG Vulkan loader.

Can you elaborate a bit on what is involved? I'm interested to learn more.

**Comment by mtavenrath** [comment]
>>Multi-Instance support is not (yet) supported and would require some changes to the LunarG Vulkan >>loader.
>Can you elaborate a bit on what is involved? I'm interested to learn more.

Looking at https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#initialization-functionpointers calling vkInstanceGetProcAddr with a NULL instance for anything except 	
vkEnumerateInstanceExtensionProperties, vkEnumerateInstanceLayerProperties, or 	
vkCreateInstance will result in a nullptr. Thus there's no way to get an instance independent trampoline function for extensions while there are instance indepdent trampoline functions for the vulkan core and a few WSI extensions. Since multiple instances might have different extensions enabled it makes sense to have this behaviour. On the other side it prevents fetching instance independent trampolines.

**Comment by cubanismo** [comment]
That's by design though.  Applications (and wrapper libraries) are supposed to track per-instance functions themselves.  They're free to implement their own trampoline layer.
