### ISSUE TITLE
Passing a vk:: struct to a c API call

### ISSUE THREAD

**Issue by msc-** [KhronosGroup/Vulkan-Hpp#75]
I want to convert an existing program to use vulkan.hpp. As I am trying to do a little at a time, I want to pass the C++ structs  & handles to Vk c functions.
```
vk::CommandBufferBeginInfo cmdBufInfo({}, nullptr);
vkBeginCommandBuffer(drawCmdBuffers[i], &cmdBufInfo);
```
produces the error
```
error: cannot convert ‘vk::CommandBufferBeginInfo*’ to ‘const VkCommandBufferBeginInfo*’
```
I suppose I am doing it wrong but I have tried just about everything I can think of and just keep getting various compile errors. The only thing that has worked is doing a reinterpret_cast myself.
``` 
vkBeginCommandBuffer(vkctx.drawCmdBuffers[i],
        	reinterpret_cast<const VkCommandBufferBeginInfo*>(&cmdBufInfo));
```
but since there is an operator in the class to do this, it shouldn't be necessary. What am I doing wrong?

Even the reinterpret_cast doesn't work if I create cmdBufInfo by
```
vk::CommandBufferBeginInfo cmdBufInfo();
```
In this case at the call to vkBeginCommandBuffer I get
```
undefined reference to `cmdBufInfo()'
```
Apparently it thinks cmdBufInfo is a function. This is confusing me too as the constructor has defaults for all its arguments.

I am using a 64-bit system, Ubuntu 16.10.

**Comment by msc-** [comment]
I see the operator is actually a cast to a reference not to a pointer. This works fine:
```
const VkCommandBufferBeginInfo& cbbi = cmdBufInfo;
```
Am I missing some syntax that would let me pass cmdBufInfo to a Vk function without an explicit cast or is my use case just not supported?

**Comment by spfuetzner** [comment]
I find it a bit shady that Vulkan-hpp does the cast to '''const VkCommandBufferBeginInfo&''' by a reinterpret_cast. It is formally undefined behaviour and only works by chance. Because we also want nice wrapper classes as members it can also not be solved by storing a VkCommandBufferBeginInfo directly in the class. I would disallow the mix of C- and C++-API for the utility classes like vk::CommandBufferBeginInfo. Apparently they choosed the way it is now and maybe all that is left to make your example work is an additional '''operator const VkCommandBufferBeginInfo*() const'''.

**Comment by spfuetzner** [comment]
This should also work:
'''vkBeginCommandBuffer(drawCmdBuffers[i], &static_cast<const VkCommandBufferBeginInfo&>(cmdBufInfo));'''

**Comment by mtavenrath** [comment]
Passing Vulkan-Hpp to Vulkan C functions is not the default operation and adding the cast makes more clear what's going on than a (implicit) operator which returns the pointer of an Vulkan-Hpp struct. Closing.
