### ISSUE TITLE
Allow for conversion of vk::StructureChain to a reference of its first element

### ISSUE THREAD

**Issue by kiroma** [KhronosGroup/Vulkan-Hpp#784]
Passing in a structure chain into a function requires getting its first element. Having to type in something like `.get<vk::MemoryAllocateInfo>()` every time may get rather cumbersome, and even using `std::get<0>` may result in weird looking code.
I propose 2 solutions, add an implicit type conversion operator which returns the reference to the first element, something like
```cpp
private:
template<typename T1, typename... Ts>
struct First
{
	typedef T1 type;
};
template<typename T1>
struct First<T1>
{
	typedef T1 type;
};
public:
operator typename First<ChainElements...>::type&()
{
	return std::get<0>(*this);
}
```
Or, if the implicit type conversions aren't preferred, a member function `first()` which does the same thing
```cpp
typename First<ChainElements...>::type& first()
{
	return std::get<0>(*this);
}
```

**Comment by kiroma** [comment]
Name of the function is up for debate, I'm hearing opinions about borrowing naming from std with `.front()`, also implicit conversion operator is viewed as generally less favorable.
If this gets approval I can go ahead with a PR.

**Comment by Wunkolo** [comment]
I was looking into this before myself as well a while ago.

I like this, there is a `static_assert` that protects against removing the first element of the structure chain so at the very least the first structure in the structure-chain should always be there and available to be referenced into while any of the other elements can be unlinked in and out.

I like the explicit cast of the entire structure chain into the type of the first element and even considered using the `*` operator to "dereference" the entire structure chain into the type of the first element. The whole `pNext`-chain pattern keeps up this concept of an entire chain of elements being supplemental to the main structure being passed in.

To me, a `vk::StructureChain<vk::MemoryAllocateInfo,...>` is "a structure that is at _least_ a `vk::MemoryAllocateInfo`". So rather than "front" implying the structure is ordinal or depends on the order of elements(_even though it's a singly linked list, it acts more like a tree of depth 1 as each entry in the `pNext` enhances/extends just the root of the tree_), I think we can maintain the concept of the entire `vk::StructureChain<vk::MemoryAllocateInfo,...>` being an abstraction for a single extended `vk::MemoryAllocateInfo` and maybe even just use `get()` or `operator*` or allowing an explicit cast like `(vk::MemoryAllocateInfo)memoryAllocInfoChain`.

**Comment by kiroma** [comment]
Yeah, using `.get()` without any template parameters or arguments is the first thing I instinctively went for so this may be a better idea.

**Comment by asuessenbach** [comment]
We're extending the currently available function get<>() to have the first element of the StructureChain as its default type, thus allowing
auto & root = structureChain.get();
