### ISSUE TITLE
Use C++20 std::span in place of ArrayProxy

### ISSUE THREAD

**Issue by kwarkGorny** [KhronosGroup/Vulkan-Hpp#817]
Hi,
Starting from C++20 there is std::span which like ArrayProxy is non owning view over contigus collection of object in memory. It currently has support from all major compilers so it would be nice to have some overloads accepting std::span or it could replace  ArrayProxy if  used compiler support it or by adding special macro to enable it (like VULKAN_HPP_ENABLE_STD_SPAN)

Regards,
kwarkGorny

**Comment by asuessenbach** [comment]
Sounds like a nice idea, but unfortunately, std::span misses some constructors provided by ArrayProxy: construction out of a nullptr, out of a single element, and out of an initializer list. In addition to that, the constructor out of a size and a pointer expects the arguments in different order.
That is, I don`t see how std::span could replace ArrayProxy.
I could imagine to add additional function flavours, taking a std::span instead of an ArrayProxy, but I don't see what that would get you.
