### ISSUE TITLE
Multiple definitions compiler error in vulkan_raii.hpp

### ISSUE THREAD

**Issue by Kasys** [KhronosGroup/Vulkan-Hpp#895]
I am using vulkan_raii.hpp in a multiple file project. I ran into the issue of getting multiple definition compiler errors from those stray function definitions. Shouldn't those be contained in a source file?

Also unrelated to that issue unless defining VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1 vk::raii::Context is trying to use the static dispatcher which doesn't have an init funciton. I am not sure if it shouldn't use the static dispatcher or the usage is just wrong.

**Comment by asuessenbach** [comment]
> Also unrelated to that issue...

If you don't explicitly define `VULKAN_HPP_RAII_DISPATCHER_TYPE`, it is defined to be `VULKAN_HPP_DEFAULT_DISPATCHER_TYPE`.
If you don't explicitly define `VULKAN_HPP_DEFAULT_DISPATCHER_TYPE`, it is defined to be `::VULKAN_HPP_NAMESPACE::DispatchLoaderDynamic` if `VULKAN_HPP_DISPATCH_LOADER_DYNAMIC`  is defined to be `1` or `::VULKAN_HPP_NAMESPACE::DispatchLoaderStatic`, otherwise.
If you don't explicitly define `VULKAN_HPP_DISPATCH_LOADER_DYNAMIC`, it is defined to be `1` if `VK_NO_PROTOTYPES` is defined or `0`, otherwise.

**Comment by Kasys** [comment]
Yeah i figured that VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1 or VK_NO_PROTOTYPES needs to be defined for the raii-handles to work. However i was worried about that not being the intended behaviour, since the raii examples don't include this define.

**Comment by asuessenbach** [comment]
I have to admit, that definition is a little hidden...
As all raii samples depend on the samples/utils.lib, VULKAN_HPP_DISPATCH_LOADER_DYNAMIC is pulled in to all those samples with a 1.

**Comment by Kasys** [comment]
Oh it never occurred to me to look into the makefile for defines. Thank you for the clarification.
