### ISSUE TITLE
Functions dispatched with DispatchLoaderDynamic do not (always) trigger validation layer callbacks

### ISSUE THREAD

**Issue by Kasys** [KhronosGroup/Vulkan-Hpp#909]
I am using vulkan.hpp via vulkan_raii.hpp to access the vulkan api.

Recently while refactoring my project I forgot to enable the VK_KHR_surface extension which is needed to use `vkGetPhysicalDeviceSurfaceSupportKHR`.
After searching around for the culprit of the crash I found it to be `vk::raii::PhysicalDevice::getSurfaceSupportKHR`, which calls `vkGetPhysicalDeviceSurfaceSupportKHR` through the dynamic dispatcher. Because i didn't know why it was crashing i tried replacing the function with a call to `vkGetPhysicalDeviceSurfaceSupportKHR`, statically linked from VulkanSDK\1.2.170.0\Lib\vulkan-1.lib. That produced a validation message telling me, that the VK_KHR_surface extension needs to be enabled to use `vkGetPhysicalDeviceSurfaceSupportKHR`.

I don't really know what is going wrong here, or if this is even intended behaviour. I ran the error message test from the end of RAII_Samples/EnableValidationWithCallback/EnableValidationWithCallback.cpp and that worked fine, before and after having the issue with vkGetPhysicalDeviceSurfaceSupportKHR.

**Comment by asuessenbach** [comment]
First of all, if you "just" forgot to enable the VK_KHR_surface extension, but not the corresponding platform extension (like VK_KHR_win32_surface), you should get a validation error telling you just that.
Besides that, yes, that's the expected behavior. If you don't enable an extension, the functions for that extension are either not even loaded, or resolved to nullptr.
I could add an assertion with a comment hinting to the potentially missed extension to catch such cases in a more controlled manner.

**Comment by Kasys** [comment]
You're totally right, because of some code reordering `glfwInit` wasn't called before `glfwGetRequiredInstanceExtensions`, so both extension weren't getting enabled.
I don't know wether doing these kind of assertions fits the scope of vulkan_raii, but if it does I think it should be a good solution for that kind of usage error, since when using a statically linked library the validation layers would catch that kind of error.
