### ISSUE TITLE
Warning when checking vk::UniqueHandle after pipeline creation

### ISSUE THREAD

**Issue by ichlubna** [KhronosGroup/Vulkan-Hpp#919]
Hi, 
I got a warning that
`vk::ResultValue<vk::UniqueHandle<Type, Dispatch> >::operator vk::UniqueHandle<Type, Dispatch>() [with Type = vk::Pipeline; Dispatch = vk::DispatchLoaderStatic]’ is deprecated: Implicit-cast operators on vk::ResultValue are deprecated. Explicitly access the value as member of ResultValue. [-Wdeprecated-declarations]`
when using:
`if(!(graphicsPipeline = device->createGraphicsPipelineUnique({}, createInfo)))`
this, however, does not happen with other unique handles such as for example:
`if(!(commandPool = device->createCommandPoolUnique(createInfo)))`
Why the inconsitency? What is the right usage then?
Thanks

**Comment by asuessenbach** [comment]
The reason for this inconsistency is, that the creation of a GraphicsPipeline allows more an additional success code (ePipelineCompileRequiredEXT). That requires, that createGraphicsPipelineUnique returns ResultValue<UniqueHandle<Pipeline>>, instead of just a UniquePipeline.
That is, in order to get your UniqueGraphicsPipeline, you would need to code something like this:
```
    vk::ResultValue<vk::UniquePipeline> rv = device.createGraphicsPipelineUnique( nullptr, graphicsPipelineCreateInfo );
    switch ( rv.result )
    {
      case vk::Result::eSuccess:
          graphicsPipeline = std::move( rv.value );
          break;
      case vk::Result::ePipelineCompileRequiredEXT:
        // something meaningfull here
        break;
      default: assert( false );  // should never happen
    }
```
Note that, unless you explicitly defined VULKAN_HPP_NO_EXCEPTIONS before including vulkan.hpp, you don't need to check if the UniqueHandle you get is valid. It either is valid, you an exception was fired.

**Comment by ichlubna** [comment]
Thank you very much @asuessenbach! That makes sense.
